id: AA3198CDE
title: fC0F3
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:29:49.432357
  last_modified_at: 2022-05-27 16:29:49.432360
